INSERT INTO products (name, brand, product_type, price, rating, description, image_url) VALUES
    ('Timberland 6" Premium Waterproof Boots', 'Timberland', 'Boot', 220.00, 4.5, 'Waterproof leather boot with a padded collar and a rugged lug sole.', '/static/products/timberland-6-inch-boot.png'),
    ('Nike Air Force 1 Low', 'Nike', 'Sneaker', 90.00, 4.6, 'Classic low-top leather sneaker with Air cushioning.', '/static/products/nike-air-force-1-low.png'),
    ('Crocs Classic Clogs', 'Crocs', 'Clog', 50.00, 4.8, 'Lightweight foam clog with ventilation holes and a pivoting heel strap.', '/static/products/crocs-classic-clog.png'),
    ('Adidas Ultraboost Light', 'Adidas', 'Running Shoe', 190.00, 4.7, 'Responsive running shoe with a breathable knit upper and cushioned midsole.', '/static/products/adidas-ultraboost-light.png'),
    ('Dr. Martens 1460 Smooth Leather Boots', 'Dr. Martens', 'Boot', 170.00, 4.6, 'Iconic lace-up boot with smooth leather and an air-cushioned sole.', '/static/products/dr-martens-1460.png'),
    ('Vans Old Skool', 'Vans', 'Skate Shoe', 75.00, 4.7, 'Low-top skate shoe with the signature side stripe and durable waffle outsole.', '/static/products/vans-old-skool.png'),
    ('Converse Chuck Taylor All Star', 'Converse', 'Sneaker', 65.00, 4.6, 'Canvas high-top sneaker with a rubber toe cap and classic star patch.', '/static/products/converse-chuck-taylor.png'),
    ('New Balance 574 Core', 'New Balance', 'Sneaker', 85.00, 4.5, 'Heritage sneaker with suede and mesh panels and cushioned everyday support.', '/static/products/new-balance-574.png'),
    ('Puma Suede Classic XXI', 'Puma', 'Sneaker', 70.00, 4.4, 'Retro suede sneaker with a padded collar and rubber outsole.', '/static/products/puma-suede-classic.png'),
    ('Reebok Club C 85', 'Reebok', 'Sneaker', 80.00, 4.5, 'Clean tennis-inspired sneaker with a leather upper and cushioned sockliner.', '/static/products/reebok-club-c-85.png'),
    ('Asics Gel-Kayano 30', 'Asics', 'Running Shoe', 160.00, 4.7, 'Stability running shoe with supportive guidance and soft gel cushioning.', '/static/products/asics-gel-kayano-30.png'),
    ('Brooks Ghost 15', 'Brooks', 'Running Shoe', 140.00, 4.8, 'Smooth daily trainer with balanced cushioning and a breathable mesh upper.', '/static/products/brooks-ghost-15.png'),
    ('Hoka Clifton 9', 'Hoka', 'Running Shoe', 145.00, 4.7, 'Lightweight running shoe with a high-cushion midsole and rocker geometry.', '/static/products/hoka-clifton-9.png'),
    ('Saucony Ride 16', 'Saucony', 'Running Shoe', 130.00, 4.6, 'Versatile road shoe with responsive foam and a comfortable engineered mesh upper.', '/static/products/saucony-ride-16.png'),
    ('On Cloud 5', 'On', 'Running Shoe', 140.00, 4.5, 'Everyday performance shoe with CloudTec cushioning and a speed-lacing system.', '/static/products/on-cloud-5.png'),
    ('Jordan 1 Retro High OG', 'Jordan', 'Basketball Shoe', 180.00, 4.8, 'High-top basketball sneaker with classic color blocking and responsive cushioning.', '/static/products/jordan-1-retro-high.png'),
    ('Nike Dunk Low', 'Nike', 'Sneaker', 115.00, 4.7, 'Low-profile sneaker with layered leather panels and a padded tongue.', '/static/products/nike-dunk-low.png'),
    ('Adidas Samba OG', 'Adidas', 'Sneaker', 100.00, 4.8, 'Low-profile indoor-training sneaker with a leather upper and gum rubber outsole.', '/static/products/adidas-samba-og.png'),
    ('Nike Air Max 90', 'Nike', 'Sneaker', 130.00, 4.6, 'Retro-inspired sneaker with visible Air cushioning and layered mesh panels.', '/static/products/nike-air-max-90.png'),
    ('Adidas Stan Smith', 'Adidas', 'Sneaker', 95.00, 4.5, 'Minimal leather sneaker with perforated three-stripe details.', '/static/products/adidas-stan-smith.png'),
    ('Birkenstock Arizona Soft Footbed', 'Birkenstock', 'Sandal', 135.00, 4.7, 'Two-strap sandal with a contoured cork footbed and soft suede lining.', '/static/products/birkenstock-arizona.png'),
    ('Teva Original Universal Sandals', 'Teva', 'Sandal', 55.00, 4.6, 'Quick-drying outdoor sandal with adjustable straps and a durable outsole.', '/static/products/teva-original-universal.png'),
    ('Chaco Z/Cloud Sandals', 'Chaco', 'Sandal', 105.00, 4.7, 'Supportive sport sandal with adjustable webbing and a cushioned footbed.', '/static/products/chaco-z-cloud.png'),
    ('Vionic Tide II Sandals', 'Vionic', 'Sandal', 75.00, 4.4, 'Casual flip-flop with built-in arch support and a soft microfiber lining.', '/static/products/vionic-tide-ii.png'),
    ('Clarks Desert Boot', 'Clarks', 'Boot', 150.00, 4.6, 'Classic ankle boot with a suede upper and a lightweight crepe outsole.', '/static/products/clarks-desert-boot.png'),
    ('Red Wing Classic Moc Toe', 'Red Wing', 'Boot', 329.00, 4.8, 'Heritage work boot with moc-toe construction and a traction wedge sole.', '/static/products/red-wing-classic-moc.png'),
    ('Blundstone 500 Chelsea Boots', 'Blundstone', 'Boot', 210.00, 4.7, 'Slip-on Chelsea boot with elastic side panels and a durable leather upper.', '/static/products/blundstone-500.png'),
    ('Sorel Caribou Waterproof Boots', 'Sorel', 'Boot', 200.00, 4.6, 'Insulated winter boot with waterproof construction and a rugged rubber shell.', '/static/products/sorel-caribou.png'),
    ('Hunter Original Tall Rain Boots', 'Hunter', 'Rain Boot', 165.00, 4.5, 'Waterproof rubber rain boot with a durable treaded outsole.', '/static/products/hunter-original-tall.png'),
    ('UGG Classic Mini II Boots', 'UGG', 'Boot', 150.00, 4.7, 'Short suede boot lined with soft wool and finished with a lightweight outsole.', '/static/products/ugg-classic-mini-ii.png'),
    ('Steve Madden Lando Loafers', 'Steve Madden', 'Loafer', 90.00, 4.3, 'Modern slip-on loafer with a polished upper and a low stacked heel.', '/static/products/steve-madden-lando.png'),
    ('Cole Haan OriginalGrand Wingtip', 'Cole Haan', 'Dress Shoe', 170.00, 4.5, 'Refined wingtip shoe combining brogue details with lightweight cushioning.', '/static/products/cole-haan-originalgrand.png'),
    ('Allen Edmonds Park Avenue', 'Allen Edmonds', 'Dress Shoe', 395.00, 4.8, 'Elegant cap-toe Oxford crafted from premium leather for formal occasions.', '/static/products/allen-edmonds-park-avenue.png'),
    ('Clarks Wallabee', 'Clarks', 'Moccasin', 140.00, 4.6, 'Distinctive moccasin-inspired shoe with a crepe sole and suede upper.', '/static/products/clarks-wallabee.png'),
    ('Toms Alpargata Classic', 'Toms', 'Slip-On', 60.00, 4.4, 'Lightweight canvas slip-on with a cushioned insole and flexible outsole.', '/static/products/toms-alpargata-classic.png'),
    ('Sperry Authentic Original 2-Eye', 'Sperry', 'Boat Shoe', 100.00, 4.5, 'Classic boat shoe with genuine leather laces and a non-marking rubber sole.', '/static/products/sperry-authentic-original.png'),
    ('Moccasin House Driving Moc', 'Moccasin House', 'Moccasin', 85.00, 4.2, 'Soft leather driving moccasin with a flexible pebble outsole.', '/static/products/moccasin-house-driving-moc.png'),
    ('Allbirds Tree Runners', 'Allbirds', 'Running Shoe', 100.00, 4.4, 'Breathable everyday runner made with a lightweight eucalyptus fiber upper.', '/static/products/allbirds-tree-runners.png'),
    ('Veja Campo Leather', 'Veja', 'Sneaker', 175.00, 4.5, 'Minimal leather sneaker with a recycled polyester lining and rubber outsole.', '/static/products/veja-campo.png'),
    ('Common Projects Original Achilles', 'Common Projects', 'Sneaker', 425.00, 4.6, 'Premium minimalist sneaker with a smooth leather upper and tonal styling.', '/static/products/common-projects-achilles.png'),
    ('Salomon XT-6', 'Salomon', 'Trail Shoe', 200.00, 4.7, 'Technical trail shoe with aggressive traction and a supportive quick-lacing system.', '/static/products/salomon-xt-6.png'),
    ('Merrell Moab 3 Hiking Shoes', 'Merrell', 'Hiking Shoe', 110.00, 4.6, 'Durable hiking shoe with protective toe reinforcement and grippy outsole.', '/static/products/merrell-moab-3.png'),
    ('Keen Targhee III Waterproof', 'Keen', 'Hiking Shoe', 165.00, 4.5, 'Waterproof hiking shoe with a roomy toe box and dependable trail traction.', '/static/products/keen-targhee-iii.png'),
    ('La Sportiva Tarantulace', 'La Sportiva', 'Climbing Shoe', 90.00, 4.4, 'Entry-level climbing shoe with a comfortable fit and sticky rubber sole.', '/static/products/la-sportiva-tarantulace.png'),
    ('Nike Pegasus 40', 'Nike', 'Running Shoe', 130.00, 4.7, 'Versatile road-running shoe with springy foam and breathable engineered mesh.', '/static/products/nike-pegasus-40.png'),
    ('Under Armour Charged Assert 10', 'Under Armour', 'Running Shoe', 75.00, 4.3, 'Lightweight running shoe with responsive cushioning and durable outsole pods.', '/static/products/under-armour-charged-assert-10.png'),
    ('Mizuno Wave Rider 27', 'Mizuno', 'Running Shoe', 140.00, 4.5, 'Smooth daily trainer with Wave cushioning and a secure mesh upper.', '/static/products/mizuno-wave-rider-27.png'),
    ('Fila Disruptor 2', 'Fila', 'Sneaker', 80.00, 4.2, 'Chunky lifestyle sneaker with a padded collar and sculpted platform outsole.', '/static/products/fila-disruptor-2.png'),
    ('Reef Santa Ana Flip Flops', 'Reef', 'Flip-Flop', 35.00, 4.3, 'Comfortable beach sandal with a cushioned footbed and water-friendly straps.', '/static/products/reef-santa-ana.png'),
    ('Rainbow Premier Leather Sandals', 'Rainbow', 'Sandal', 60.00, 4.6, 'Durable leather sandal with a contoured footbed and layered sole construction.', '/static/products/rainbow-premier.png'),
    ('Aldo Stessy Ballet Flats', 'Aldo', 'Flat', 70.00, 4.1, 'Versatile ballet flat with a rounded toe and softly cushioned insole.', '/static/products/aldo-stessy-flats.png'),
    ('Sam Edelman Loraine Loafers', 'Sam Edelman', 'Loafer', 150.00, 4.5, 'Polished horsebit loafer with a structured silhouette and supportive footbed.', '/static/products/sam-edelman-loraine.png');